version: "3"

services:
  http:
    dns:
      - "1.1.1.1"
      - "1.0.0.1"

  dns:
    dns:
      - "1.1.1.1"
      - "1.0.0.1"
    environment:
      LANCACHE_IP: "10.0.0.3"

  sni:
    dns:
      - "1.1.1.1"
      - "1.0.0.1"
